# github-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-pvc
  namespace: github
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: github-azurefile