name: Build image, push to ACR, deploy to AKS
concurrency: 
  group: deployment

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy application
    runs-on: github-runner
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Install Azure CLI, kubectl
        run: chmod +x install_libs.sh && ./install_libs.sh

      - name: Install kubelogin
        run: sudo az aks install-cli
      
      - name: Login with workload identity
        run: az login --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --federated-token $(cat $AZURE_FEDERATED_TOKEN_FILE)

      - name: Build image with AZ ACR
        run: |
          az acr build -f /runner/_work/github-runner/github-runner/Dockerfile -t githubacr14149.azurecr.io/github-demo:${{ github.sha }} -r githubacr14149 .
      
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group github-runner-rg --name aks-github-runner --overwrite-existing
          export KUBECONFIG=/home/runner/.kube/config
          kubelogin convert-kubeconfig -l workloadidentity

      - name: Deploy application
        run: |
          sed 's|IMAGE|githubacr14149.azurecr.io/github-demo|g; s/TAG/${{ github.sha }}/g' /runner/_work/github-runner/github-runner/pod.yaml | kubectl apply -f -