name: Build image, push to ACR, deploy to AKS
concurrency: 
  group: deployment

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy application
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Login with workload identity
        run: az login --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID --federated-token $(cat $AZURE_FEDERATED_TOKEN_FILE)

      - name: Build image with AZ ACR
        run: |
          az acr build -f /actions-runner/_work/github-runner/github-runner/Dockerfile -t githubacr12713.azurecr.io/github-demo:${{ github.sha }} -r githubacr12713 .
      
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group github-runner-rg --name aks-github-runner --overwrite-existing
          kubelogin convert-kubeconfig -l workloadidentity

      - name: Deploy application
        run: |
          sed 's|IMAGE|githubacr12713.azurecr.io/github-demo|g; s/TAG/${{ github.sha }}/g' /actions-runner/_work/github-runner/github-runner/pod.yaml | kubectl apply -f -
